### ISSUE TITLE
Submodules are broken

### ISSUE THREAD

**Issue by Fulgen301** [gitMarky/Hazard#1]
`.gitignore` contains Library_Shooter and Library_ArenaGames, which breaks updating the submodules because the paths specified in `.gitmodules` don't exist.

**Comment by gitMarky** [comment]
I see. The problem is that it wants to stage them when I commit stuff, that's why I included them in .gitignore. However, if that also means that you cannot update them, then I'll remove the .gitignore entries. Thanks for the explanation!
